# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:securitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
security.jwt.secret=7ae29fbcd6e248af9c6239cde39bc2aa8e63fbef861d4d0fb88d53ef85852c54
security.jwt.issuer=ifsp-security-api
security.jwt.expiration-minutes=240
